import path from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";
import type { Role } from "@farooq/shared";

const here = path.dirname(fileURLToPath(import.meta.url));

export const E2E_DIR = path.resolve(here, "..");
export const REPO_DIR = path.resolve(E2E_DIR, "../..");
export const RUN_DIR = path.join(E2E_DIR, ".run");
export const ARTIFACTS_DIR = path.join(E2E_DIR, "e2e-artifacts");
export const STATE_FILE = path.join(RUN_DIR, "state.json");

// 127.0.0.1 (not "localhost") on both sides: one host name, so the session cookie is shared and there is no IPv4/IPv6 guessing.
export const API_PORT = Number(process.env.E2E_API_PORT ?? 3100);
export const WEB_PORT = Number(process.env.E2E_WEB_PORT ?? 4173);
export const API_URL = `http://127.0.0.1:${API_PORT}`;
export const WEB_URL = `http://127.0.0.1:${WEB_PORT}`;

export const E2E_ROLES: Role[] = ["OWNER", "MANAGER", "ACCOUNTANT", "SALES", "INVENTORY"];

export interface E2eUser {
  username: string;
  password: string;
  name: string;
  storageState: string;
}
export interface E2eState {
  apiUrl: string;
  webUrl: string;
  users: Record<Role, E2eUser>;
}

/** Read by the specs (in the worker processes) — the passwords were generated by global setup and exist nowhere else. */
export function readState(): E2eState {
  return JSON.parse(readFileSync(STATE_FILE, "utf8")) as E2eState;
}
