-- S13: the purchase search (generated by drizzle-kit, nothing hand-written). The purchase's own folded fields are stored columns; what follows
-- other tables is read per request: the supplier's CURRENT text (suppliers.search_text, S4), each line as printed (purchase_items.search_text) and
-- each line product's CURRENT text (products.search_text: what the legacy Purchases toolbar searched, pTxt). The payment status (a filter, not a word
-- to search) is derived at query time from the allocations of POSTED vouchers, never stored.
ALTER TABLE "products" ADD COLUMN "search_text" text GENERATED ALWAYS AS (COALESCE(search_join(name_ur, name_en, brand_en, category, legacy_doc->>'cat', sku, legacy_id, legacy_doc->>'kg'), '') || chr(1) || COALESCE(search_join(legacy_doc->>'sourceFolio', legacy_doc->>'normalizedName', legacy_doc->>'nameEn'), '')) STORED;--> statement-breakpoint
ALTER TABLE "purchase_items" ADD COLUMN "search_text" text GENERATED ALWAYS AS (search_join(description_en_snapshot, description_snapshot, brand_snapshot, package_snapshot)) STORED;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "search_numbers" text GENERATED ALWAYS AS (search_join(purchase_number, search_compact(purchase_number), supplier_invoice_no, search_compact(supplier_invoice_no), delivery_ref)) STORED;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "search_supplier" text GENERATED ALWAYS AS (fold_search(supplier_name_snapshot)) STORED;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "search_amount" text GENERATED ALWAYS AS (search_amount_text(total_p)) STORED;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "search_date" text GENERATED ALWAYS AS (search_date_text(date)) STORED;--> statement-breakpoint
ALTER TABLE "purchases" ADD COLUMN "search_other" text GENERATED ALWAYS AS (search_join(vehicle_no, search_compact(vehicle_no), driver, warehouse_snapshot, notes, description)) STORED;